import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";
import Footer from "components/footer/footer";
import Header from "components/layout/header/Header";
import NeedHelp from "components/NeedHelp/NeedHelp";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-Inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Header />
        {children}
        <NeedHelp />
        <Footer />
      </body>
    </html>
  );
}
